spring:
  cloud:
    gateway:
      routes:
        - id: member
          uri: lb://MEMBER/
          predicates:
            - Path=/member/**
          filters:
            - RewritePath=/member/(?<path>.*),/$\{path}
        - id: observe-search
          uri: lb://OBSERVE-SEARCH/
          predicates:
            - Path=/observe-search/**
          filters:
            - RewritePath=/observe-search/(?<path>.*),/$\{path}
        - id: observe-site
          uri: lb://OBSERVE-SITE/
          predicates:
            - Path=/observe-site/**
          filters:
            - RewritePath=/observe-site/(?<path>.*),/$\{path}
        - id: sample
          uri: lb://SAMPLE/
          predicates:
            - Path=/sample/**
          filters:
            - RewritePath=/sample/(?<path>.*),/$\{path}
        - id: starcard
          uri: lb://STARCARD/
          predicates:
            - Path=/starcard/**
          filters:
            - RewritePath=/starcard/(?<path>.*),/$\{path}
        - id: chat
          uri: lb://CHAT/
          predicates:
            - Path=/chat/**
          filters:
            - RewritePath=/chat/(?<path>.*),/$\{path}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true # 이것을 true로 설정하여 Eureka 레지스트리에서 서비스 정보를 가져올 수 있도록 합니다.
    serviceUrl:
      defaultZone: http://k9a101.p.ssafy.io:8761/eureka/ # 여기에 Eureka 서버의 호스트와 포트를 지정합니다.
